language : python

python:
  - 3.6
 

before_script:
  - pip install -r requirements.txt

script:
  - cd TDD
  - python3 -m pytest --cov ../TDD --cov-report term-missing

after_script:
  - coveralls
  
